name: CI/CD Pipeline with Docker and EC2

on:
  pull_request:
    branches: [ "main" ]
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Give execute permission to gradlew
        run: chmod +x ./backend/spring/gradlew

      - name: Build with Gradle
        run: |
          cd backend/spring
          ./gradlew build -x test

      - name: Build Docker image
        run: |
          docker build -t orre:$GITHUB_SHA -f backend/spring/Dockerfile .
      
      - name: Push Docker image to registry
        run: |
          docker tag orre:$GITHUB_SHA ${{ secrets.DOCKER_USERNAME }}/orre:$GITHUB_SHA
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/orre:$GITHUB_SHA


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Pulling Docker image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/orre:$GITHUB_SHA
            echo "Stopping existing container if it exists..."
            docker stop orre || true
            echo "Removing existing container if it exists..."
            docker rm orre || true
            echo "Running new container..."
            docker run -d --name orre -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/orre:$GITHUB_SHA
            echo "Deployment completed."  
